stages:
    - build
    - test

# Unit tests

build-unit-tests:
    stage: build
    before_script:
        - docker compose -f docker/docker-compose.yml --env-file ${env} down --remove-orphans
    script:
        - docker compose -f docker/docker-compose.yml --env-file ${env} build backend_unit_tests test_db

unit-tests:
    stage: test
    before_script:
        - docker compose -f docker/docker-compose.yml --env-file ${env} down --remove-orphans
    script:
        - docker compose -f docker/docker-compose.yml --env-file ${env} run backend_unit_tests
    after_script:
        - docker compose -f docker/docker-compose.yml --env-file ${env} down --remove-orphans

# Integration tests
#  
# build-integration-tests:
#     stage: build
#     before_script:
#         - make integration_tests_clean PERSONAL=0
#     script:
#         - make integration_tests_build PERSONAL=0
#  
# integration-tests:
#     stage: test
#     before_script:
#         - make integration_tests_clean PERSONAL=0
#     script:
#         - make integration_tests PERSONAL=0
#     after_script:
#         - make integration_tests_clean PERSONAL=0

