
services:
  nginx:
    build:
      context: ..
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../server/media/:/static/img

  backend:
    build:
      context: ../backend/
    restart: always
    ports:
      - "127.0.0.1:12345:80"
    environment:
      APP_PHOTO_BASE_URL: "/img"
      APP_PHOTO_PATH_MAIN: "/server/media"
      APP_PHOTO_PATH_TEMP: "/server/temp"
      APP_SWAGGER_CONF_URL: "/docs/openapi.json"
      DB_AUTH_NAME: "authentication"
      DB_MAIN_NAME: "rent_market"
      DB_HOST: "postgresql_db"
      DB_PORT: "5432"
      DB_USER_NAME: "postgres"
      DB_USER_PASSWORD: "postgres"
    volumes:
      - ../server/media/:/server/media
      - ../server/temp/:/server/temp

  postgresql_db:
    build:
      context: ../scripts/psql/.
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /mnt/rent_market:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.org
      - PGADMIN_DEFAULT_PASSWORD=psswd
    volumes:
      - ./pgadmin/:/var/lib/pgadmin
    ports:
      - "127.0.0.1:42069:80"


