
services:
  backend:
    build:
      context: ../
    restart: always
    links:
      - "postgresql_db:database"
    ports:
      - "127.0.0.1:12345:80"
    environment:
      APP_PHOTO_BASE_URL: "http://localhost/static"
      APP_PHOTO_PATH_MAIN: "/server/media"
      APP_PHOTO_PATH_TEMP: "/server/temp"
      DB_AUTH_NAME: "authentication"
      DB_MAIN_NAME: "rent_market"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER_NAME: "postgres"
      DB_USER_PASSWORD: "postgres"

  postgresql_db:
    build:
      context: ../scripts/psql/.
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /mnt/rent_market:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.org
      - PGADMIN_DEFAULT_PASSWORD=psswd
    volumes:
      - ./pgadmin/:/var/lib/pgadmin
    ports:
      - "127.0.0.1:42069:80"


