// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../implementation/mock/pickuppoint/repository.go
//

// Package mock_pickuppoint is a generated GoMock package.
package mock_pickuppoint

import (
	reflect "reflect"
	models "rent_service/internal/domain/models"
	collection "rent_service/internal/misc/types/collection"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockIRepository) GetAll() (collection.Collection[models.PickUpPoint], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(collection.Collection[models.PickUpPoint])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIRepository)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockIRepository) GetById(pickUpPointId uuid.UUID) (models.PickUpPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", pickUpPointId)
	ret0, _ := ret[0].(models.PickUpPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIRepositoryMockRecorder) GetById(pickUpPointId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIRepository)(nil).GetById), pickUpPointId)
}

// MockIPhotoRepository is a mock of IPhotoRepository interface.
type MockIPhotoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPhotoRepositoryMockRecorder
	isgomock struct{}
}

// MockIPhotoRepositoryMockRecorder is the mock recorder for MockIPhotoRepository.
type MockIPhotoRepositoryMockRecorder struct {
	mock *MockIPhotoRepository
}

// NewMockIPhotoRepository creates a new mock instance.
func NewMockIPhotoRepository(ctrl *gomock.Controller) *MockIPhotoRepository {
	mock := &MockIPhotoRepository{ctrl: ctrl}
	mock.recorder = &MockIPhotoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPhotoRepository) EXPECT() *MockIPhotoRepositoryMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockIPhotoRepository) GetById(pickUpPointId uuid.UUID) (collection.Collection[uuid.UUID], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", pickUpPointId)
	ret0, _ := ret[0].(collection.Collection[uuid.UUID])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIPhotoRepositoryMockRecorder) GetById(pickUpPointId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIPhotoRepository)(nil).GetById), pickUpPointId)
}

// MockIWorkingHoursRepository is a mock of IWorkingHoursRepository interface.
type MockIWorkingHoursRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkingHoursRepositoryMockRecorder
	isgomock struct{}
}

// MockIWorkingHoursRepositoryMockRecorder is the mock recorder for MockIWorkingHoursRepository.
type MockIWorkingHoursRepositoryMockRecorder struct {
	mock *MockIWorkingHoursRepository
}

// NewMockIWorkingHoursRepository creates a new mock instance.
func NewMockIWorkingHoursRepository(ctrl *gomock.Controller) *MockIWorkingHoursRepository {
	mock := &MockIWorkingHoursRepository{ctrl: ctrl}
	mock.recorder = &MockIWorkingHoursRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkingHoursRepository) EXPECT() *MockIWorkingHoursRepositoryMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockIWorkingHoursRepository) GetById(pickUpPointId uuid.UUID) (models.PickUpPointWorkingHours, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", pickUpPointId)
	ret0, _ := ret[0].(models.PickUpPointWorkingHours)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIWorkingHoursRepositoryMockRecorder) GetById(pickUpPointId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIWorkingHoursRepository)(nil).GetById), pickUpPointId)
}
